### ISSUE TITLE
Mailosaur init method incorrect definition for not required parameters

### ISSUE THREAD

**Issue by gmzcarlos** [mailosaurapp/mailosaur-python#2]
def __init__(self, mailbox, api_key, base_url, smtp_host):
        self.mailbox = mailbox
        self.api_key = api_key
        self.base_url = base_url or 'https://mailosaur.com/api'
        self.smtp_host = smtp_host or 'mailosaur.in'

should be

def __init__(self, mailbox, api_key, base_url='https://mailosaur.com/api', smtp_host= 'mailosaur.in'):
        self.mailbox = mailbox
        self.api_key = api_key
        self.base_url = base_url
        self.smtp_host = smtp_host

**Comment by mailosaurapp** [comment]
Thanks, this one is now fixed, we'll be pushing this to PyPI later this evening.

**Comment by mailosaurapp** [comment]
We have released a new client library version 3.0.1 and removed the sleep and retries to make your email tests go a little bit faster. (They are no longer required)
